version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/src/bosh_release/"
    schedule:
      interval: "daily"

####################################
# Settings for branch v2.3 used in:
# https://github.com/cloudfoundry/persi-ci/blob/3ed769b9b522d4fcbe0dc9bf6dcf7168f0b21b40/sync-pipelines.sh#L64
####################################
  - package-ecosystem: "bundler"
    target-branch: "v2.3"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    target-branch: "v2.3"
    directory: "/"
    schedule:
      interval: "daily"

####################################
# Settings for branch v5.0 used in:
# https://github.com/cloudfoundry/persi-ci/blob/3ed769b9b522d4fcbe0dc9bf6dcf7168f0b21b40/sync-pipelines.sh#L56
####################################
  - package-ecosystem: "bundler"
    target-branch: "v5.0"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    target-branch: "v5.0"
    directory: "/"
    schedule:
      interval: "daily"      
  - package-ecosystem: "gomod"
    target-branch: "v5.0"
    directory: "/src/bosh_release/"
    schedule:
      interval: "daily"
