#!/bin/bash

set -x -e

version=`cat nfs-volume-version/number`
tarball_name=nfs-volume-$version.tgz
pushd nfs-volume-release
  bosh -n create-release --version=$version --force --tarball=$tarball_name
  mv $tarball_name ../created-nfs-volume-release
popd
