#!/bin/bash

set -e -x -u

source $(pwd)/nfs-volume-release/scripts/ci/utils.sh
check_param BOSH_TARGET
check_param BOSH_USERNAME
check_param BOSH_PASSWORD
check_param ENVIRONMENT_NAME
check_param DEPLOYMENTS_DIR
check_param INFRASTRUCTURE

if [ -z "$ENVIRONMENT_NAME" ]; then
  environment_path="${PWD}/${DEPLOYMENTS_DIR}"
else
  environment_path="${PWD}/${DEPLOYMENTS_DIR}/${ENVIRONMENT_NAME}"
fi

stubs_path="${environment_path}/stubs"
templates_path="${environment_path}/templates"
nfsvolume_stubs="${PWD}/${DEPLOYMENTS_DIR}/nfs-volume/stubs"

mkdir -p generated-manifest-nfs

pushd cf-release
  ./scripts/generate_deployment_manifest \
    ${INFRASTRUCTURE} \
    ${stubs_path}/cf/*.yml \
    > ../generated-manifest-nfs/cf-deployment.yml
popd

pushd nfs-volume-release

cat > ${PWD}/nfsbroker-creds.yml << EOF
---
properties:
  nfsbroker:
    username: ${BOSH_USERNAME}
    password: ${BOSH_PASSWORD}
EOF

  ./scripts/generate_manifest.sh \
    ../generated-manifest-nfs/cf-deployment.yml \
    ${nfsvolume_stubs}/director-uuid.yml \
    ${nfsvolume_stubs}/iaas.yml \
    ${PWD}/nfsbroker-creds.yml

  mv nfsvolume-aws-manifest.yml ../generated-manifest-nfs/nfsvolume-manifest.yml
popd

