#!/bin/bash
# vim: set ft=sh

set -e -x

pushd nfs-volume-release
    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    cd src/code.cloudfoundry.org/nfsbroker

    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress . "$@"
popd
