#!/bin/bash

set -x -e

### Install kinit
sudo apt-get update
sudo apt-get --assume-yes install krb5-user

### Get a kerberos ticket for SHARE1@PERSI.CF_APP.COM

######################################################################################
#### prepare for acceptance
######################################################################################

pushd nfs-volume-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ./scripts/run-kerbdriver-cert-tests -race
popd
