#!/bin/bash
# vim: set ft=sh

set -e -x

cd nfs-volume-release-concourse-tasks

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

./scripts/run-broker-unit-tests
