#!/bin/bash
# vim: set ft=sh

set -e -x

{
    cd credhub
    # need to patch the script from credhub repo to use the -legacy flag to export the keytool certs, else newer java versions will fail
    sed -i  's#pass:changeit#pass:changeit -legacy#g' scripts/setup_dev_mtls.sh
    ./scripts/start_server.sh -Dspring.profiles.active=dev,dev-h2 > /tmp/start_credhub.log 2>&1
    kill -9 "$(ps --pid $$ -oppid=)"; exit
}&

until curl -f -v http://localhost:9001/health; do
    sleep 10;
done

cp credhub/applications/credhub-api/src/test/resources/server_ca_cert.pem /tmp/server_ca_cert.pem

pushd nfs-volume-release
    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH
    export GO111MODULE=on
    cd src/code.cloudfoundry.org/nfsbroker

    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress . "$@"
popd
