#!/bin/bash
# vim: set ft=sh

set -e -x

scripts_path=./$(dirname $0)/..
eval $($scripts_path/get_paths.sh)

if [ "$(uname)" == "Darwin" ]; then
    export GOPATH=`greadlink -f ${scripts_path}/..`
else
    export GOPATH=`readlink -f ${scripts_path}/..`
fi
export PATH=$GOPATH/bin:$PATH

source ${scripts_path}/ci/utils.sh
check_param CF_USERNAME
check_param CF_PASSWORD
check_param CF_API_ENDPOINT
check_param APPS_DOMAIN
check_param SERVICE_NAME
check_param PLAN_NAME
check_param BROKER_URL
check_param BROKER_USER
check_param BROKER_PASSWORD
check_param SERVER_ADDRESS
check_param SHARE
check_param BIND_CONFIG
check_param TEST_MULTI_CELL
check_param TEST_MOUNT_OPTIONS
check_param TEST_READ_ONLY

if [ -z "$APPLICATION_PATH" ]; then
    echo "APPLICATION_PATH cannot be blank"
    exit 1
fi

pushd ${scripts_path}/../src/code.cloudfoundry.org/nfsbroker
  GOOS=linux GOARCH=amd64 go build -o bin/nfsbroker
  export BROKER_APPLICATION_PATH=$PWD

  if [ -n "$PUSHED_BROKER_NAME" ]; then
cat << EOF > manifest.yml
---
  buildpack: binary_buildpack
  env:
    DBDRIVERNAME: ${DB_DRIVER_NAME}
    SERVICENAME: ${SERVICE_NAME}
    USERNAME: ${BROKER_USER}
    PASSWORD: ${BROKER_PASSWORD}
    LOGLEVEL: debug
    DBHOST: ${DB_HOST}
    DBPORT: ${DB_PORT}
    DBNAME: ${DB_NAME}
    DB_USERNAME: ${DB_USERNAME}
    DB_PASSWORD: ${DB_PASSWORD}
    ALLOWED_OPTIONS: "uid,gid,auto_cache,username,password"
EOF

  fi
popd

go get github.com/onsi/ginkgo/ginkgo

${scripts_path}/run-pats \
${CF_USERNAME} \
${CF_PASSWORD} \
${CF_API_ENDPOINT} \
${APPS_DOMAIN} \
${SERVICE_NAME} \
${PLAN_NAME} \
${BROKER_URL} \
${BROKER_USER} \
${BROKER_PASSWORD} \
${SERVER_ADDRESS} \
${SHARE} \
${BIND_CONFIG} \
${PUSHED_BROKER_NAME} \
${DB_SERVICE_INSTANCE_NAME}
