#!/bin/bash

set -x -e

### Install kinit
sudo apt-get update
export DEBIAN_FRONTEND=noninteractive
sudo apt-get --assume-yes install dialog krb5-user

cat /etc/krb5.conf | sed -e 's/default_realm = ATHENA.MIT.EDU/default_realm = PERSI.CF-APP.COM/' > /tmp/krb5.conf
mv -f /tmp/krb5.conf /etc/krb5.conf

### Get a kerberos ticket for SHARE1@PERSI.CF_APP.COM
ktutil <<EOT
addent -password -p share1@PERSI.CF-APP.COM -k 1 -e aes256-cts

wkt /tmp/share1.keytab
EOT
export KEYTAB=`cat /tmp/share1.keytab | base64 | awk '{printf "%s",$0}END{print""}'`

######################################################################################
#### prepare for acceptance
######################################################################################

pushd nfs-volume-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ./scripts/run-kerbdriver-cert-tests -race
popd
