#!/bin/bash
# vim: set ft=sh

set -ex

cd nfs-volume-release

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

if ! ginkgo version &> /dev/null
then
  go get -u github.com/onsi/ginkgo/ginkgo
fi

./scripts/run-driver-unit-tests -race
