#!/bin/bash

set -x -e

/start.sh &

function kill_ganesha {
    pkill -9 ganesha || true
}

trap kill_ganesha EXIT

SOURCE="localhost:/"
export SOURCE
export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH
go get -u github.com/onsi/ginkgo/ginkgo

pushd mapfs-release
  export PATH=$PWD/bin:$PATH

  mkdir -p /var/vcap/packages/mapfs/bin/
  pushd src/mapfs
    go build -mod=vendor -o "/var/vcap/packages/mapfs/bin/mapfs" *.go
  popd
popd

pushd nfs-volume-release
  NFS_ACCEPTANCE_DIR="${PWD}/tmp"
  mkdir -p "${NFS_ACCEPTANCE_DIR}"

  listen_address=0.0.0.0:7589

  drivers_path="${NFS_ACCEPTANCE_DIR}/voldriver_plugins"
  mkdir -p $drivers_path
  chmod 777 $drivers_path

  if [ "$TRANSPORT" == "tcp" ]
      then
          listen_address=0.0.0.0:7589
          driver_address=http://$listen_address
  else
      listen_address=$drivers_path/nfsv3driver.sock
      driver_address=$drivers_path/nfsv3driver.sock
  fi

  export FIXTURE_FILENAME="${NFS_ACCEPTANCE_DIR}/fixture.json"
  cat << EOT > "${FIXTURE_FILENAME}"
{
  "volman_driver_path": "${drivers_path}",
  "driver_address": "${driver_address}",
  "driver_name": "nfsv3driver",
  "create_config": {
    "Name": "nfs-volume-name",
    "Opts": {"source":"${SOURCE}","uid":"2000","gid":"2000"}
  }
}
EOT

  pushd src/code.cloudfoundry.org/nfsv3driver
    GO111MODULE=on go build -mod=vendor -o "${NFS_ACCEPTANCE_DIR}/nfsv3driver" "cmd/nfsv3driver/main.go"

    export PATH=$PATH:$PWD
    mkdir -p "${NFS_ACCEPTANCE_DIR}/mountdir"

    export DRIVER_CMD="${NFS_ACCEPTANCE_DIR}/nfsv3driver"
    export DRIVER_OPTS="-listenAddr="$listen_address",-transport="$TRANSPORT",-driversPath="$drivers_path""
  popd


  mkdir -p src/code.cloudfoundry.org/docker_driver_integration_tests
  cp -R ../docker_driver_integration_tests/* src/code.cloudfoundry.org/docker_driver_integration_tests


  function kill_ganesha {
    pkill -9 ganesha || true
  }

  trap kill_ganesha EXIT
  pushd src/code.cloudfoundry.org/${TEST_PACKAGE}
    GO111MODULE=on ginkgo -v -keepGoing . -race
  popd
  rm -rf "${NFS_ACCEPTANCE_DIR}"
popd
