#!/bin/bash

set -x -e

sudo apt-get update
sudo apt-get --assume-yes install autoconf automake libtool xsltproc libfuse-dev fuse nfs-common

pushd lib-nfs
    libtoolize
    aclocal
    autoheader
    autoconf
    automake --add-missing
    ./configure
    make install
popd

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

pushd fuse-nfs
    ./setup.sh
    ./configure
    make
    make install
popd

service rpcbind start || true
sleep 5

pushd nfs-volume-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ./scripts/run-experimental-driver-cert -race
popd
