#!/bin/bash
# vim: set ft=sh

set -e -x

scripts_path=./$(dirname $0)/..
eval $($scripts_path/get_paths.sh)

if [ "$(uname)" == "Darwin" ]; then
    export GOPATH=`greadlink -f ${scripts_path}/..`
else
    export GOPATH=`readlink -f ${scripts_path}/..`
fi
export PATH=$GOPATH/bin:$PATH

source ${scripts_path}/ci/utils.sh
check_param CF_USERNAME
check_param CF_PASSWORD
check_param CF_API_ENDPOINT
check_param APPS_DOMAIN
check_param SERVICE_NAME
check_param PLAN_NAME
check_param BROKER_URL
check_param BROKER_USER
check_param BROKER_PASSWORD
check_param SERVER_ADDRESS
check_param SHARE

if [ -z "$APPLICATION_PATH" ]; then
    echo "APPLICATION_PATH cannot be blank"
    exit 1
fi

pushd ${scripts_path}/../src/code.cloudfoundry.org/nfsbroker
  ./cp_files.sh
  export BROKER_APPLICATION_PATH=$PWD
popd

go get github.com/onsi/ginkgo/ginkgo

${scripts_path}/run-pats \
${CF_USERNAME} \
${CF_PASSWORD} \
${CF_API_ENDPOINT} \
${APPS_DOMAIN} \
${SERVICE_NAME} \
${PLAN_NAME} \
${BROKER_URL} \
${BROKER_USER} \
${BROKER_PASSWORD} \
${SERVER_ADDRESS} \
${SHARE} \
${PUSHED_BROKER_NAME} \
${SQL_SERVICE_NAME}
