#!/bin/bash

set -x -e

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install autoconf automake libtool xsltproc libfuse-dev fuse nfs-common

pushd lib-nfs
    libtoolize
    aclocal
    autoheader
    autoconf
    automake --add-missing
    ./configure
    make install
popd

pushd fuse-nfs
    ./setup.sh
    ./configure
    make
    make install
popd

setcap 'cap_net_bind_service=+ep' /usr/local/bin/fuse-nfs

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

######################################################################################
#### prepare for acceptance
######################################################################################

FUSE_MOUNT="$(cat nfs-volume-info/fuse-nfs-volume-info)"
export FUSE_MOUNT
NFS_MOUNT="$(cat nfs-volume-info/nfs-volume-info)"
export NFS_MOUNT

pushd nfs-volume-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ginkgo -v src
popd
