#!/bin/bash

set -ex

if [[ -z "${CONFIG_FILE_PATH}" ]]; then
  echo "Missing required CONFIG_FILE_PATH parameter."
  exit 1
fi

export CONFIG="${PWD}/${CONFIG_FILE_PATH}"

if [[ ! -r "${CONFIG}" ]]; then
  echo "Failed to read config file: ${CONFIG}"
  exit 1
fi

pushd  nfs-volume-release
  export GOPATH="${PWD}"
  export PATH="${GOPATH}/bin:${PATH}"

  pushd  src/code.cloudfoundry.org/persi-acceptance-tests
    export ASSETS_PATH=assets
    export TEST_APPLICATION_PATH="${ASSETS_PATH}/pora"

    if [[ -n "${PARALLEL_NODES}" ]]; then
      ginkgo --slowSpecThreshold=300 -r -nodes ${PARALLEL_NODES} .
    else
      ginkgo --slowSpecThreshold=300 -r -p .
    fi
  popd
popd
