#!/bin/bash

set -x -e

### Install kinit
sudo apt-get update
sudo apt-get --assume-yes install krb5-user

### Get a kerberos ticket for SHARE1@PERSI.CF_APP.COM
ktutil <<EOT
addent -password -p share1@PERSI.CF-APP.COM -k 1 -e aes256-cts

wkt /tmp/share1.keytab
EOT
export KEYTAB=`cat /tmp/share1.keytab | base64`

######################################################################################
#### prepare for acceptance
######################################################################################

pushd nfs-volume-release
    export GOROOT=/usr/local/go
    export PATH=$GOROOT/bin:$PATH

    export GOPATH=$PWD
    export PATH=$PWD/bin:$PATH

    go get github.com/onsi/ginkgo/ginkgo
    go get github.com/onsi/gomega

    ./scripts/run-kerbdriver-cert-tests -race
popd
