#!/bin/bash

install_pre_commit() {
  if [ ! -f $1 ]; then
    echo "#!/bin/bash" > $1
    chmod +x $1
  fi

  if grep -q 'git-hooks/pre-commit' $1; then
    echo "pre-commit already installed."
  else
    echo >> $1
    echo './git-hooks/pre-commit' >> $1
    echo "pre-commit installed."
  fi
}

# nfs-volume-release hooks
RELEASE=$(cd $(dirname $0)/.. && pwd)
PRE_COMMIT=${RELEASE}/.git/hooks/pre-commit
install_pre_commit ${PRE_COMMIT}

# nfsv3driver hooks
HOOKS_DIR=${RELEASE}/.git/modules/src/code.cloudfoundry.org/nfsv3driver/hooks
PRE_COMMIT=${HOOKS_DIR}/pre-commit
mkdir -p ${HOOKS_DIR}
install_pre_commit ${PRE_COMMIT}

#nfsbroker hooks
HOOKS_DIR=${RELEASE}/.git/modules/src/code.cloudfoundry.org/nfsbroker/hooks
PRE_COMMIT=${HOOKS_DIR}/pre-commit
mkdir -p ${HOOKS_DIR}
install_pre_commit ${PRE_COMMIT}

#service-broker-store hooks
HOOKS_DIR=${RELEASE}/.git/modules/src/code.cloudfoundry.org/service-broker-store/hooks
PRE_COMMIT=${HOOKS_DIR}/pre-commit
mkdir -p ${HOOKS_DIR}
install_pre_commit ${PRE_COMMIT}
