#!/bin/bash

set -ex

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)


pushd src/code.cloudfoundry.org/nfsv3driver
  go run github.com/onsi/ginkgo/v2/ginkgo -keepGoing -p -race -trace -randomizeAllSpecs -progress "$@"
popd
pushd src/code.cloudfoundry.org/nfsv3driver/cmd/nfsv3driver
  go run github.com/onsi/ginkgo/v2/ginkgo  -keepGoing -trace -race -randomizeAllSpecs -progress "$@"
popd
