#!/bin/bash

set -ex

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

export GO111MODULE=on

pushd src/code.cloudfoundry.org/nfsv3driver
  ginkgo -keepGoing -p -race -trace -randomizeAllSpecs -progress "$@"
popd
pushd src/code.cloudfoundry.org/nfsv3driver/cmd/nfsv3driver
  ginkgo -keepGoing -trace -race -randomizeAllSpecs -progress "$@"
popd
pushd src/code.cloudfoundry.org/volumedriver
  ginkgo -r -keepGoing -p -race -trace -randomizeAllSpecs -progress "$@"
popd
