#!/bin/bash

set -e -x

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

usage () {
    echo "Usage: run-pats admin_user admin_password api_host apps_domain service_name plan_name broker_url broker_user broker_password [create_config bind_config disallowed_ldap_bind_config missing_gid_bind_config create_bogus_config bind_bogus_config isolation_segment]"
    exit 1
}

if [[ "$#" -le 8 ]]
    then
        usage
fi

pushd `dirname $0`
    CONFIG=${PWD}/config
    mkdir -p ${CONFIG}
    CONFIG=${CONFIG}/pats.json
    randval=`openssl rand -hex 3`

    set +e
    which cf
    if [ $? -eq 0 ]; then
      set -e
      echo "Skipping cf cli install"
    else
      set -e
      mkdir -p cf-cli
      pushd cf-cli
        curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx
        ln -s ${PWD}/cf /bin/cf
      popd
    fi

cat << EOF > ${CONFIG}
{
      "admin_user": "${1}",
      "admin_password": "${2}",
      "api": "${3}",
      "apps_domain": "${4}",
      "service_name": "${5}",
      "plan_name": "${6}",
      "broker_url": "${7}",
      "broker_user": "${8}",
      "broker_password": "${9}",
      "skip_ssl_validation": true,
      "default_timeout": 30,
      "name_prefix": "${randval}",
      "create_config": "${10}",
      "bind_config": "${11}",
      "disallowed_ldap_bind_config": "${12}",
      "missing_gid_bind_config": "${13}",
      "create_bogus_config": "${14}",
      "bind_bogus_config": "${15}",
      "isolation_segment": "${16}"
    }
EOF

    export TEST_APPLICATION_PATH="${PWD}/../src/code.cloudfoundry.org/persi-acceptance-tests/assets/pora"
    export ASSETS_PATH="${PWD}/../src/code.cloudfoundry.org/persi-acceptance-tests/assets"

    pushd  ../src/code.cloudfoundry.org/persi-acceptance-tests
        CONFIG=${CONFIG} ginkgo --slowSpecThreshold=300 -r -nodes ${PARALLEL_NODES} .
    popd
popd
