#!/bin/bash

set -e -x

scripts_path=./$(dirname $0)
eval $($scripts_path/get_paths.sh)

usage () {
    echo "Usage: run-pats admin_user admin_password api_host apps_domain service_name plan_name broker_url broker_user broker_password server_addr share"
    exit 1
}

if [[ "$#" -le 8 ]]
    then
        usage
fi

pushd `dirname $0`
    CONFIG=${PWD}/config
    mkdir -p ${CONFIG}
    CONFIG=${CONFIG}/pats.json

    set +e
    which cf
    if [ $? -eq 0 ]; then
      set -e
      echo "Skipping cf cli install"
    else
      set -e
      mkdir -p cf-cli
      pushd cf-cli
        curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar -zx
        ln -s ${PWD}/cf /bin/cf
      popd
    fi

cat << EOF > ${CONFIG}
{
      "admin_user": "${1}",
      "admin_password": "${2}",
      "api": "${3}",
      "apps_domain": "${4}",
      "service_name": "${5}",
      "plan_name": "${6}",
      "broker_url": "${7}",
      "broker_user": "${8}",
      "broker_password": "${9}",
      "skip_ssl_validation": true,
      "default_timeout": 30,
      "name_prefix": "PATs",
      "server_addr": "${10}",
      "share": "${11}",
      "bind_config": "{\"uid\":\"1000\",\"gid\":\"1000\"}",
      "pushed_broker_name": "${12}",
      "mysql_service_name": "${13}"
    }
EOF

    export TEST_APPLICATION_PATH="${PWD}/../src/code.cloudfoundry.org/persi-acceptance-tests/assets/pora"

    pushd  ../src/code.cloudfoundry.org/persi-acceptance-tests
        CONFIG=${CONFIG} ginkgo  --slowSpecThreshold=300 -r .
    popd
popd
