#!/bin/bash

set -e -x

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list -app code.cloudfoundry.org/nfsv3driver/cmd/...

  # separate test and binary dependencies
  gosub list -test code.cloudfoundry.org/nfsv3driver/...

  gosub list -app github.com/cloudfoundry-community/nfsbroker/cmd/...
  gosub list -test github.com/cloudfoundry-community/nfsbroker/...
  gosub list -test code.cloudfoundry.org/persi-acceptance-tests/...
} > /tmp/packages

cat /tmp/packages | xargs gosub sync
